### ISSUE TITLE
USER STORY: BUDDY SYSTEM

### ISSUE THREAD

**Issue by DarrachBarneveld** [KaiLangen96/january-hackathon-2024#55]
As a **user** I can **add friends** so that **I can have joint savings goals**

# Acceptance Criteria
a. Users can add friends
b. Friends savings goals are visible and contributable 

# Tasks
- [ ] Create a toggle friends button
- [ ] List all possible users
- [ ] Render all friends savings goals
- [ ] Allow contribution to friends savings goals
