### ISSUE TITLE
USER STORY: CUSTOM ERROR PAGES

### ISSUE THREAD

**Issue by Aylamccarthy** [KaiLangen96/january-hackathon-2024#8]
As a **user** I can **see a custom error message when I navigate to a broken link** so that **I can go back to the homepage**

# Acceptance Criteria
a. The website has a custom 404/403/500 error pages

# Tasks
- [x] Create custom 403 error page
- [x] Create custom 404 error page
- [x] Create custom 500 error page
